Upgrade to LLVM 21
With version 17, compilation of the selftests fails with:

    In file included from progs/stream.c:8:
    /bpf-next/tools/testing/selftests/bpf/bpf_arena_common.h:47:15: error: conflicting types for 'bpf_arena_alloc_pages'
    47 | void __arena* bpf_arena_alloc_pages(void *map, void __arena *addr, __u32 page_cnt,
    | ^
    /bpf-next/tools/testing/selftests/bpf/tools/include/vmlinux.h:152158:14: note: previous declaration is here
    152158 | extern void *bpf_arena_alloc_pages(void *p__map, void *addr__ign, u32 page_cnt, int node_id, u64 flags) __weak __ksym;
    | ^

Signed-off-by: Paul Chaignon <paul.chaignon@gmail.com>